apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-k8s
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: gabrielgasp/hello-k8s:v7
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: hello-k8s-cm
            - secretRef:
                name: hello-k8s-sct
          volumeMounts:
            - name: hello-k8s-pvc
              mountPath: /app/data
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: web
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: web
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: web
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: hello-k8s-pvc
          persistentVolumeClaim:
            claimName: hello-k8s-pvc
