apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
spec:
  selector:
    app: hello-k8s
  type: NodePort
  ports:
    - name: web
      port: 9000
      targetPort: 8080 # Or "web" (port name in deployment)
      nodePort: 30001
