apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: hello-k8s
  name: hello-k8s-sa

---
apiVersion: rbac.authorization.k8s.io/v1
# Use `kind: ClusterRole` for cluster-wide access
kind: Role
metadata:
  namespace: hello-k8s
  name: hello-k8s-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
# Use `kind: ClusterRoleBinding` for cluster-wide access
kind: RoleBinding
metadata:
  namespace: hello-k8s
  name: hello-k8s-role-binding
subjects:
  - kind: ServiceAccount
    name: hello-k8s-sa
    namespace: hello-k8s
roleRef:
  # Use `kind: ClusterRole` for cluster-wide access
  kind: Role
  name: hello-k8s-role
  apiGroup: rbac.authorization.k8s.io
